Feature/docs stark-ui testing subpackage
NationalBankBelgium/stark pull request #1906
Opened 2020-05-08 16:57 UTC by christophercr

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1600

## What is the new behavior?
The docs of the `testing` subpackage from the Stark-UI are now generated and included in the Stark API Docs.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Took the chance to increase the coverage of the documentation 👍

2020-06-25 14:39 UTC, christophercr commented on packages/stark-ui/src/modules/table/components/table.component.ts
> +	 * {@link StarkPaginationConfig} object for the embedded {@link StarkPaginationComponent} component
Indeed... much better ;)

2020-06-25 14:40 UTC, christophercr commented on packages/stark-ui/testing/src/app-sidebar.mock.ts
> +export class MockStarkAppSidebarService implements SpyObj<StarkAppSidebarService> {
True, I didn't think of that. Now I've separated it in a different commit 👍

2020-06-25 14:40 UTC, christophercr commented
@SuperITMan I've adapted the PR with the latest remarks, can you have a look?

2020-06-26 09:15 UTC, SuperITMan commented
@christophercr Thanks for the modification.
About the additional commit, it does not appear in the CHANGELOG because you didn't mention the "BREAKING CHANGES", could you adapt it ?
for instance:
```
refactor(stark-ui): renamed `MockAppSidebarService` to `MockStarkAppSidebarService` in `@nationalbankbelgium/stark-ui/testing` subpackage

BREAKING CHANGES:
Renamed `MockAppSidebarService` to `MockStarkAppSidebarService` in `@nationalbankbelgium/stark-ui/testing` subpackage
```

I know it's redundant so any other idea would be better 😊 

Normally, `refactor(stark-ui)!: ...` would be enough to display the message in the CHANGELOG but it's not the case 😕
See: https://github.com/conventional-changelog/conventional-changelog/issues/648

2020-06-26 10:10 UTC, christophercr commented
Mmm I'm no sure whether this is actually a breaking change. I mean, for the testing mocks... this is not necessarily a breaking change since the applications won't break. It will only break those unit tests where this mocks are used. So I would say we can leave it as a `fix` so it appears in the changelog. What do you think @SuperITMan ?

2020-06-26 12:03 UTC, SuperITMan commented
For me, fix is ok 👌

2020-06-29 08:54 UTC, christophercr commented
@SuperITMan I've adapted the commit message. 

Now the Travis build fails because of some linting errors in the starter... could be because of the new version of code-style. But never mind, I'm fixing these errors already in the PR for the upgrade of code-style :wink:

So I think this PRQ is ready to merge :+1:

2020-07-03 15:04 UTC, christophercr commented
@SuperITMan I've rebased this PR and now it's ready to be merged 👍

2020-08-24 12:42 UTC, christophercr commented
@SuperITMan I've rebased this PR and fixed all conflicts. It's ready to be merged :wink:

2020-08-25 22:44 UTC, SuperITMan requested changes
A small typo to fix and then we can merge this! 
Thanks again :+1:

2020-08-25 22:44 UTC, SuperITMan commented on packages/stark-ui/testing/src/app-sidebar.mock.md
> +mockStarkAppSidebarService = TetBed.get(STARK_APP_SIDEBAR_SERVICE);
Small typo: Te**s**tBed.get

2020-08-26 12:19 UTC, christophercr commented on packages/stark-ui/testing/src/app-sidebar.mock.md
> +mockStarkAppSidebarService = TetBed.get(STARK_APP_SIDEBAR_SERVICE);
Oops...

2020-08-26 12:20 UTC, christophercr commented
@SuperITMan typos fixed 😉 
The other MD files had the same typo ...

2020-08-26 13:02 UTC, SuperITMan approved these changes
LGTM :+1:

2020-08-26 13:03 UTC, SuperITMan commented
Oops, I didn't notice it for the other files... Thanks for the correction :blush:

2020-08-26 13:03 UTC, merged