feat(stark-all): add support for Docker and Kubernetes
NationalBankBelgium/stark pull request #378
Opened 2018-05-17 07:27 UTC by MrEfbiaye

I added the folder I created containing the scripts, dockerfiles and deployment files under Kubernetes.
Normally they should all be functional but it should not be forgotten that like all config files, they remain editable before use because some parameters must be changed

ISSUES CLOSED: #26

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #26 

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-05-18 06:27 UTC, SuperITMan requested changes
Some small changes to do

2018-05-18 06:27 UTC, SuperITMan commented on doc_k8s/windows/docker/stark-start/Dockerfile-start
> +RUN apt-get update -y -q && apt-get install git-sh rsync -y && apt-get upgrade -y -q
I think it makes more sense to run the upgrade before the install of git-sh and rsync.

2018-05-18 06:27 UTC, SuperITMan commented on doc_k8s/linux/docker/Dockerfile.script
> +#### It is necessary to adapt the script according to the address of the private register
Why not adding a parameter in your options to customize the registry address if needed?

2018-05-18 06:27 UTC, SuperITMan commented on doc_k8s/linux/docker/Dockerfile.script
> +#!/bin/bash
I think the extension .script is not really obvious and does allow to suppose this is a bash/sh script.
Could you please adapt the extension for .sh?

2018-06-02 19:20 UTC, dsebastien commented
@MrEfbiaye est-ce que tu penses terminer ceci ou pas?

2026-06-01 19:50 UTC, closed without merging